### ISSUE TITLE
[Request] Have DQM3 Talents also list child talents in addition to parent talents when in detail view.

### ISSUE THREAD

**Issue by Snaid1** [MetalKid/DQM3_Database#2]
I'm trying to plan out my talents for breeding in the future and I would find it helpful if, in addition to listing what the parent talents are, it would list the child talents that this talent is a parent for. That way I could easily look at a talent my monster has and see what other talents I could develop it into.

**Comment by MetalKid** [comment]
I can do that, but it'll need to be a calculated file. The website I have that uses this data makes that sort of thing easy to use. Anyone that takes the raw data I have, the data is there to support this in reverse if need be. Adding in the data the other way in the database itself would require 2 points of keeping that data in-sync, which is something a real database wouldn't want to do here.  I'll see what I can do.

**Comment by Snaid1** [comment]
Makes sense. Having it calculated for the website works for me. Thanks!

**Comment by MetalKid** [comment]
Hopefully this is what you were looking for:

https://github.com/MetalKid/DQM3_Database/blob/main/data/computed/Talents.json

**Comment by Snaid1** [comment]
That's exactly what I was looking for! Thank you!
